# Generated by Django 3.2.8 on 2021-10-29 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('millati', models.CharField(max_length=40)),
                ('fuqaroligi', models.CharField(max_length=40)),
                ('malumoti', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sertificat_nomi', models.CharField(max_length=55)),
                ('stipendiya', models.CharField(default='Beruniy,Navoiy stipendiyasi', max_length=255)),
                ('yutuq1', models.FileField(default='Diplom, faxriy yorliq', upload_to='achievments')),
                ('yutuq2', models.FileField(blank=True, default='Diplom, faxriy yorliq', upload_to='achievments')),
                ('yutuq3', models.FileField(blank=True, default='Diplom, faxriy yorliq', upload_to='achievments')),
                ('yutuq4', models.FileField(blank=True, default='Diplom, faxriy yorliq', upload_to='achievments')),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chet_tili', models.CharField(max_length=255)),
                ('sertifikat_turi', models.CharField(default='ielts,toefl', max_length=255)),
                ('darajasi', models.FloatField(default=4.5)),
                ('seretifikat', models.FileField(upload_to='sertifikat')),
            ],
        ),
        migrations.CreateModel(
            name='Otm_turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otm_nomi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScientificAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risola', models.FileField(upload_to='ilmiy_yutuq')),
                ('jurnal', models.FileField(upload_to='ilmiy_yutuq')),
                ('conference', models.FileField(upload_to='ilmiy_yutuq')),
                ('gazeta', models.FileField(upload_to='ilmiy_yutuq')),
            ],
        ),
        migrations.CreateModel(
            name='Stipendiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stipendiya', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='TanlovMAlumotlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rektor_xati', models.FileField(upload_to='tanlov/')),
                ('kengash_bayonnomasi', models.FileField(upload_to='tanlov/')),
                ('i_r_hulosasi', models.FileField(upload_to='tanlov/')),
                ('dekan_tavsiyasi', models.FileField(upload_to='tanlov/')),
                ('stipendiya_nomzodligi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stipendiya')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=' Ali', max_length=155)),
                ('middlename', models.CharField(default='Alimov', max_length=155)),
                ('born_date', models.DateTimeField()),
                ('telefon', models.IntegerField(default=-1107)),
                ('passport', models.CharField(default='pasport seriasi,raqami,jshshr raqami', max_length=21)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aboutstudent')),
            ],
        ),
        migrations.CreateModel(
            name='Otm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reyting_daftarchasi', models.FileField(upload_to='reyting_daftarchasi/')),
                ('talim_turi', models.CharField(choices=[('Magistratura', 'Magistratura'), ('Bakalavir', 'Bakalavir')], max_length=300)),
                ('talim_shali', models.CharField(choices=[('kunduzgi', 'kunduzgi talim'), ('kechki', 'kechki talim'), ('sirtqi', 'sirtqi')], max_length=300)),
                ('talim_bosqici', models.IntegerField(default=1)),
                ('otm_nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.otm_turi')),
            ],
        ),
    ]
